acl localhost src 127.0.0.1/32 ::1
acl to_localhost dst 127.0.0.0/8 0.0.0.0/32 ::1
acl SSL_ports port 443-444
acl Safe_ports port 1025-65535
acl Safe_ports port 21
acl Safe_ports port 210
acl Safe_ports port 280
acl Safe_ports port 443-444
acl Safe_ports port 488
acl Safe_ports port 591
acl Safe_ports port 70
acl Safe_ports port 777
acl Safe_ports port 80
acl CONNECT method CONNECT
http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow all
http_access allow localhost
http_access deny all
http_port 3128
http_port 8080
hierarchy_stoplist cgi-bin ?
logformat combined %>a|%>p|%tg|%rm|%ru|HTTP/%rv|%>Hs|%st|%>st|%<st|"%{Referer}>h"|"%{User-Agent}>h"|%Ss:%Sh
coredump_dir /var/spool/squid
cache deny all
refresh_pattern ^ftp:		1440	20%	10080
refresh_pattern ^gopher:	1440	0%	1440
refresh_pattern -i (/cgi-bin/|\?) 0	0%	0
refresh_pattern .		0	20%	4320
ignore_expect_100 on
logformat splunk_json_squid {"duration": "%tr", "source.ip": "%>a", "source.port": "%>p", "destination.ip": "%<a", "destination.port": "%<p", "user_ident": "%ui", "user_name": "%un", "local_time": "[%tl]", "http_method": "%rm", "request_method_from_client": "%<rm", "request_method_to_server": "%>rm", "uri": "%ru", "http_referrer": "%{Referer}>h", "http_user_agent": "%{User-Agent}>h", "status": "%>Hs", "vendor_action": "%Ss", "dest_status": "%Sh", "total_time_milliseconds": "%<tt", "http_content_type": "%mt", "bytes": "%st", "bytes_in": "%>st", "bytes_out": "%<st"}
access_log /var/log/squid/access.log splunk_json_squid
access_log syslog:local2 combined
