---
# Legacy currently installs sysmon to C:\windows so we will mirror that behavior here
# and update over time if warranted.
- name: Ensure Install Directory Exists
  ansible.windows.win_file:
    path: "C:\\windows\\sysmon"
    state: directory

- name: Copy Sysmon Config Template
  ansible.windows.win_template:
    src: "sysmon-config.xml.j2"
    dest: "C:\\windows\\sysmon\\sysmon-config.xml"

- name: Download Sysmon installer via win_get_url + proxy
  ansible.windows.win_get_url:
    url: "{{ sysmon_installer }}"
    dest: "C:\\windows\\sysmon\\sysmon64.exe"
    method: GET
    follow_redirects: all
    use_proxy: yes
    proxy_url: "http://{{ inet_proxy_addr }}:{{ inet_proxy_port }}"
    proxy_use_default_credential: yes
    timeout: 300
    validate_certs: no
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"

- name: Install Sysmon
  ansible.windows.win_package:
    path: C:\\windows\\sysmon\\sysmon64.exe 
    arguments: -accepteula -i C:\\windows\\sysmon\\sysmon-config.xml
    state: present
    creates_service: Sysmon64

