---
- name: Ensure hives exist
  ansible.windows.win_regedit:
    path: "{{ item.path if item.path is defined }}"
    state: "{{ item.state if item.state is defined }}"
  with_items:
    - { path: 'HKU:\.Default\Software\Microsoft\Windows\CurrentVersion\Policies\System', state: 'present' }
    - { path: 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\System', state: 'present' }
    - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization', state: 'present' }
    - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System', state: 'present' }

- name: Set UE registry keys
  ansible.windows.win_regedit:
    path: "{{ item.path if item.path is defined }}"
    name: "{{ item.name if item.name is defined }}"
    data: "{{ item.data if item.data is defined }}"
    type: "{{ item.type if item.type is defined }}"
    state: "{{ item.state if item.state is defined }}"
  with_items:
    - { path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Personalization', name: 'NoLockScreen', data: '1', type: 'dword', state: 'present' }
    - { path: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon', name: 'ForceUnlockLogon', data: '1', type: 'dword', state: 'present' }
    - { path: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon', name: 'DisableLockWorkstation', data: '1', type: 'dword', state: 'present' }
    - { path: 'HKCU:\Control Panel\Desktop', name: 'ScreenSaveActive', data: '0', type: 'string', state: 'present' }
    - { path: 'HKCU:\Control Panel\Desktop', name: 'ScreenSaveTimeOut', data: '0', type: 'string', state: 'present' }
    - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System', name: 'InactivityTimeoutSecs', data: '0', type: 'dword', state: 'present'}
    - { path: 'HKU:\.Default\Control Panel\Desktop', name: 'ScreenSaveActive', data: '0', type: 'string', state: 'present' }
    - { path: 'HKU:\.Default\Control Panel\Desktop', name: 'ScreenSaveTimeOut', data: '0', type: 'string', state: 'present' }

- name: Disable Windows 10 power settings
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\7516b95f-f776-4464-8c53-06167f40cc99\8EC4B3A5-6868-48c2-BE75-4F3044BE88A7
    name: ACSettingIndex
    data: 0
    type: dword
    state: present
  when: ansible_distribution == "Microsoft Windows 10 Pro"

- name: Set win 11 keys
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\SessionInfo\1
    state: present
  ignore_errors: true
  when: ansible_distribution == "Microsoft Windows 11 Enterprise"

- name: Set win 11 keys
  ansible.windows.win_regedit:
    path: "{{ item.path }}"
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: "{{ item.type }}"
    state: "{{ item.state }}"
  ignore_errors: true
  when: ansible_distribution == "Microsoft Windows 11 Enterprise"
  with_items:
    - { path: 'HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\238C9FA8-0AAD-41ED-83F4-97BE242C8F20\7bc4a2f9-d8fc-4469-b07b-33eb785aaca0', name: "Attributes", data: "2", type: "dword", state: "present" }
    - { path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\SessionInfo\1', name: "LockScreenDisplayTimeoutOverrideActive", data: "1", type: "dword", state: "present" }


- name: Run shell commands
  ansible.windows.win_shell: "{{ item }}"
  changed_when: true
  with_items:
    - "powercfg /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c"
    - "powercfg /change monitor-timeout-ac 0"
    - "powercfg /change monitor-timeout-dc 0"
    - "powercfg /change standby-timeout-ac 0"
    - "powercfg /change standby-timeout-dc 0"
    - "powercfg /SETACVALUEINDEX SCHEME_CURRENT SUB_NONE CONSOLELOCK 0"
    - "powercfg /SETDCVALUEINDEX SCHEME_CURRENT SUB_NONE CONSOLELOCK 0"
    - "powercfg /S SCHEME_CURRENT"
    - 'reg load HKU\DefaultProfile C:\Users\Default\NTUSER.DAT'
    - 'reg unload HKU\DefaultProfile'

#    - name: Reboot to take affect
#      win_reboot:
#        msg: 'Rebooting after Power/Registry Changes'
#        pre_reboot_delay: 15
#        post_reboot_delay: 60
